# This file is generated by gradle2nix.
#
# Example usage (e.g. in default.nix):
#
#     with (import <nixpkgs> {});
#     let
#       buildGradle = callPackage ./gradleEnv.nix {};
#     in
#       buildGradle {
#         envSpec = ./gradle-env.json;
#
#         src = ./.;
#
#         gradleFlags = [ "installDist" ];
#
#         installPhase = ''
#           mkdir -p $out
#           cp -r app/build/install/myproject $out
#         '';
#       }

{ stdenv, lib, buildEnv, fetchurl, gradleGen, writeText, runCommandCC, unzip, zip, autoPatchelfHook }:

{ envSpec
, pname ? null
, version ? null
, enableParallelBuilding ? true
, gradleFlags ? [ "build" ]
, gradlePackage ? null
, ... } @ args:

let
  patchJar = jar: stdenv.mkDerivation {
    name = "patched.jar";
    src = jar;

    phases = "unpackPhase buildPhase installPhase";

    nativeBuildInputs = [ unzip zip autoPatchelfHook ];

    unpackPhase = "unzip $src";
    buildPhase = "autoPatchelf .";
    installPhase = "zip -r $out *";
  };

  mkDep = depSpec: stdenv.mkDerivation {
    inherit (depSpec) name;

    src = let
        file = fetchurl {
        inherit (depSpec) urls sha256;
      };
    # Special case for aapt2-...-linux.jar, which contains a jar with an executable that will need to be patched
    in if (lib.hasSuffix "-linux.jar" depSpec.filename) then patchJar file else file;

    phases = "installPhase";

    installPhase = ''
      mkdir -p $out/${depSpec.path}
      ln -s $src $out/${depSpec.path}/${depSpec.filename}
    '';
  };

  mkRepo = project: type: deps: buildEnv {
    name = "${project}-gradle-${type}-env";
    paths = map mkDep deps;
  };

  mkInitScript = projectSpec:
    let
      repos = builtins.mapAttrs (mkRepo projectSpec.name) projectSpec.dependencies;
    in
      writeText "init.gradle" ''
        gradle.settingsEvaluated {
          it.pluginManagement.repositories {
            clear()
            maven { url = uri("${repos.plugin}") }
          }
        }

        gradle.projectsLoaded {
          allprojects {
            buildscript {
              repositories {
                clear()
                maven { url = uri("${repos.buildscript}") }
              }
            }
            repositories {
              clear()
              maven { url = uri("${repos.project}") }
            }
          }
        }
      '';

  mkGradle = gradleSpec:
    gradleGen.gradleGen {
      inherit (gradleSpec) nativeVersion;

      name = "gradle-${gradleSpec.version}-${gradleSpec.type}";

      src = fetchurl {
        inherit (gradleSpec) url sha256;
      };
    };

  mkProjectEnv = projectSpec: {
    inherit (projectSpec) name version;
    initScript = mkInitScript projectSpec;
    gradle = args.gradlePackage or mkGradle projectSpec.gradle;
  };

  gradleEnv = builtins.mapAttrs
    (_: p: mkProjectEnv p)
    (let
    # Reach into the dependency spec and manually add a missing dependency: aapt2
      oldSpec = builtins.fromJSON (builtins.readFile ./gradle-env.json);
      aaptVersion = "3.4.1-5326820";
    in lib.recursiveUpdate oldSpec { "".dependencies.project = oldSpec."".dependencies.project ++ [
      {
        name = "com.android.tools.build-aapt2-${aaptVersion}-jar";
        filename = "aapt2-${aaptVersion}-linux.jar";
        path = "com/android/tools/build/aapt2/${aaptVersion}";
        urls = [ "https://dl.google.com/dl/android/maven2/com/android/tools/build/aapt2/${aaptVersion}/aapt2-${aaptVersion}-linux.jar" ];
        sha256 = "0cqsjnrs6wfrsk07yisd2pqyh7kpb3nacxdb6gl3fvw8hslm5220";
      }
    ]; });

  projectEnv = gradleEnv."";
  pname = args.pname or projectEnv.name;
  version = args.version or projectEnv.version;

in stdenv.mkDerivation (args // {

  inherit pname version;

  nativeBuildInputs = (args.nativeBuildInputs or []) ++ [ projectEnv.gradle ];

  buildPhase = args.buildPhase or ''
    runHook preBuild

    (
    set -x
    env \
      "GRADLE_USER_HOME=$(mktemp -d)" \
      gradle --offline --no-daemon --no-build-cache \
        --info --full-stacktrace --warning-mode=all \
        ${lib.optionalString enableParallelBuilding "--parallel"} \
        --init-script ${projectEnv.initScript} \
        ${builtins.concatStringsSep " " gradleFlags}
    )

    runHook postBuild
  '';

  dontStrip = true;
})
