#!/usr/bin/env bash

set -e
USER_AGENT="WireGuard-AndroidROMBuild/0.2 ($(uname -a))"

while read -r distro package version _; do
	if [[ $distro == upstream && $package == kmodtools ]]; then
		VERSION="$version"
		break
	fi
done < <(curl -A "$USER_AGENT" -LSs --connect-timeout 30 https://build.wireguard.com/distros.txt)

[[ -n $VERSION ]]


sed -i "s:revision=\"[^m\"]*\":revision=\"refs/tags/$VERSION\":g" wireguard.xml
