# This file was generated by https://github.com/kamilchm/go2nix v1.3.0
[
  {
    goPackagePath = "cloud.google.com/go";
    fetch = {
      type = "git";
      url = "https://code.googlesource.com/gocloud";
      rev = "9dab157497282bedd6dc12347d27fde50cd37222";
      sha256 = "0p8h1vmi4bily9wg1vhiqi26pk93pk8lk3ixbwcclhjg6g137p3q";
    };
  }
  {
    goPackagePath = "github.com/danjacques/gofslock";
    fetch = {
      type = "git";
      url = "https://github.com/danjacques/gofslock";
      rev = "0a45f885bc37dab4affc578e5b8fdc9ce6fa0364";
      sha256 = "1bw6jn0r629bjb3qsm35x4ggrm8dypyrlzgxn1yb6r88d68i9dkj";
    };
  }
  {
    goPackagePath = "github.com/golang/protobuf";
    fetch = {
      type = "git";
      url = "https://github.com/golang/protobuf";
      rev = "ed6926b37a637426117ccab59282c3839528a700";
      sha256 = "0fynqrim022x9xi2bivkw19npbz4316v4yr7mb677s9s36z4dc4h";
    };
  }
  {
    goPackagePath = "github.com/julienschmidt/httprouter";
    fetch = {
      type = "git";
      url = "https://github.com/julienschmidt/httprouter";
      rev = "08a3b3d20bbeeab9ca4889bcdb65fec0423ef882";
      sha256 = "1kd649cmmwfl8q802k56g4rzdy3xbjvy90djj11wfq98ka3xnsiy";
    };
  }
  {
    goPackagePath = "github.com/maruel/subcommands";
    fetch = {
      type = "git";
      url = "https://github.com/maruel/subcommands";
      rev = "967e945be48bc4df686f64d0ff2aac67e9d1b6ec";
      sha256 = "1baigh3yz5r0imxgricd5kzkskh59r24cpf66k5vmfm3kkski518";
    };
  }
  {
    goPackagePath = "github.com/mitchellh/go-homedir";
    fetch = {
      type = "git";
      url = "https://github.com/mitchellh/go-homedir";
      rev = "af06845cf3004701891bf4fdb884bfe4920b3727";
      sha256 = "0ydzkipf28hwj2bfxqmwlww47khyk6d152xax4bnyh60f4lq3nx1";
    };
  }
  {
    goPackagePath = "github.com/op/go-logging";
    fetch = {
      type = "git";
      url = "https://github.com/op/go-logging";
      rev = "970db520ece77730c7e4724c61121037378659d9";
      sha256 = "1cpna2x5l071z1vrnk7zipdkka8dzwsjyx7m79xk0lr08rip0kcj";
    };
  }
  {
    goPackagePath = "github.com/texttheater/golang-levenshtein";
    fetch = {
      type = "git";
      url = "https://github.com/texttheater/golang-levenshtein";
      rev = "eb6844b05fc6f7e10932b0621c7f5f7e8890541d";
      sha256 = "1xjp0zkkpax85xyya5sispvxl7axjncn7g4qbswxmrya7i6j7ycx";
    };
  }
  {
    goPackagePath = "golang.org/x/crypto";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/crypto";
      rev = "e9b2fee46413994441b28dfca259d911d963dfed";
      sha256 = "18sz5426h320l9gdll9n43lzzxg2dmqv0s5fjy6sbvbkkpjs1m28";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "c0dbc17a35534bf2e581d7a942408dc936316da4";
      sha256 = "1f1xqh2cvr629fkg9n9k347vf6g91jkrsmgmy8hlqdrq163blb54";
    };
  }
  {
    goPackagePath = "golang.org/x/oauth2";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/oauth2";
      rev = "858c2ad4c8b6c5d10852cb89079f6ca1c7309787";
      sha256 = "1dc7n8ddph8w6q0i3cwlgvjwpf2wlkx407va1ydnazasi1j5ixrw";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "ac6580df4449443a05718fd7858c1f91ad5f8d20";
      sha256 = "14gvx65w5lddi20s4wypbbvbg9ni3m8777jhp9nqxhixc61k3dyi";
    };
  }
  {
    goPackagePath = "golang.org/x/text";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/text";
      rev = "cbf43d21aaebfdfeb81d91a5f444d13a3046e686";
      sha256 = "1h6z2x4ijzd1126zk3lf8f3bp98j1irs7xg6p8nwpymkqkw5laq8";
    };
  }
  {
    goPackagePath = "google.golang.org/api";
    fetch = {
      type = "git";
      url = "https://code.googlesource.com/google-api-go-client";
      rev = "0aa2214fb2bb8d102cee8406f80891eb0aab247f";
      sha256 = "1hlhvhk9j5pmm41azcsivzvcg66w4m415f8a8l5g7qxsa8rpq2zv";
    };
  }
  {
    goPackagePath = "google.golang.org/genproto";
    fetch = {
      type = "git";
      url = "https://github.com/google/go-genproto";
      rev = "4f79533eabd1449b031c72ba945db241ea585a65";
      sha256 = "1sjapkhmzk4imxk4rvgalisgvbwi2ignsil756sdl9w977rxapk5";
    };
  }
  {
    goPackagePath = "google.golang.org/grpc";
    fetch = {
      type = "git";
      url = "https://github.com/grpc/grpc-go";
      rev = "f7b39d80aa97614c0b4420d120b59dd192d1d521";
      sha256 = "0qx8199ydd8ckm29lsg3vb1rzln6ymcbibngb45j1b5sml367rml";
    };
  }
  {
    goPackagePath = "gopkg.in/yaml.v2";
    fetch = {
      type = "git";
      url = "https://gopkg.in/yaml.v2";
      rev = "1f64d6156d11335c3f22d9330b0ad14fc1e789ce";
      sha256 = "0k5xcwkd3wmcx54isk7ck9cwp8fapfhyqdz3f13kxp77cxqizazj";
    };
  }
]
